name: spatial_random_forest
channels:
- conda-forge
- r
- ecamo19
- base
dependencies:
- r-base=4.1.1
- r-tidyverse=1.3.1
- r-randomforestsgls=0.1.4
- r-furrr=0.3.1
- r-here=1.0.1
- r-fastshap=0.0.7
- r-devtools=2.4.5
- shap=0.41.0
- parallel=20221122
- radian=0.6.4